import { createStyle } from '@/composables/useFela'
import searchLight from '@/assets/search-light.svg'
import searchDark from '@/assets/search-dark.svg'

export const navigation = {
  wrapper: createStyle(({ theme }) => ({
    display: 'flex',
    flexDirection: 'column',
    [`@media screen and (min-width: ${theme.breakPoint})`]: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
  })),
  searchQuery: createStyle(({ theme }) => ({
    width: '100%',
    marginBottom: '40px',
    padding: '16px',
    paddingLeft: '74px',
    letterSpacing: '-0.1px',
    color: theme.baseTextColor,
    fontFamily: theme.baseFontFamily,
    fontSize: '12px',
    fontWeight: theme.baseFontWeight,
    backgroundColor: theme.elementBackgroundColor,
    backgroundImage: `url(${theme.isDarkMode ? searchDark : searchLight})`,
    backgroundRepeat: 'no-repeat',
    backgroundSize: '1.5em',
    backgroundPosition: '30px 1.125em',
    border: 'none',
    borderRadius: '6px',
    boxShadow: theme.boxShadow,
    [`@media screen and (min-width: ${theme.breakPoint})`]: {
      maxWidth: '480px',
      marginRight: '24px',
      paddingTop: '19px',
      paddingRight: '16px',
      paddingBottom: '18px',
      fontSize: '14px',
    },
  })),
  countryList: createStyle(({ theme }) => ({
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, 264px)',
    gap: '40px',
    justifyContent: 'space-between',
    paddingTop: '32px',
    paddingRight: '40px',
    paddingBottom: '32px',
    paddingLeft: '40px',
    [`@media screen and (min-width: ${theme.breakPoint})`]: {
      paddingTop: '8px',
      paddingRight: 0,
      paddingBottom: '8px',
      paddingLeft: 0,
      rowGap: '76px',
    },
  })),
}

export const countrySummary = {
  wrapper: createStyle(({ theme }) => ({
    backgroundColor: theme.elementBackgroundColor,
    borderRadius: '6px',
    boxShadow: theme.boxShadow,
  })),
  flag: createStyle(() => ({
    width: '100%',
    padding: 0,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    '> img': {
      width: '100%',
      height: '160px',
      objectFit: 'cover',
      borderTopLeftRadius: '6px',
      borderTopRightRadius: '6px',
    },
  })),
  content: createStyle(() => ({
    paddingBottom: '36px',
  })),
  name: createStyle(({ theme }) => ({
    marginTop: '22px',
    marginRight: '24px',
    marginBottom: '8px',
    marginLeft: '24px',
    padding: 0,
    color: theme.baseTextColor,
    fontFamily: theme.baseFontFamily,
    fontSize: '18px',
    fontWeight: theme.boldFontWeight,
    letterSpacing: '0.2px',
    textAlign: 'left',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
  })),
  statistic: createStyle(({ theme }) => ({
    marginTop: '11px',
    marginRight: '24px',
    marginBottom: '11px',
    marginLeft: '24px',
    fontWeight: theme.lightFontWeight,
    fontSize: '13px',
    letterSpacing: '0.5px',
  })),
  statisticTitle: createStyle(({ theme }) => ({
    fontWeight: theme.baseFontWeight,
  })),
}

export const regionSelect = {
  wrapper: createStyle(() => ({
    position: 'relative',
    width: '200px',
  })),
  toggleButton: createStyle(({ theme }) => ({
    position: 'relative',
    width: '100%',
    paddingTop: '16px',
    paddingRight: '24px',
    paddingBottom: '16px',
    paddingLeft: '24px',
    color: theme.baseTextColor,
    fontFamily: theme.baseFontFamily,
    fontWeight: theme.lightFontWeight,
    fontSize: '12px',
    textAlign: 'left',
    backgroundColor: theme.elementBackgroundColor,
    border: 'none',
    borderRadius: '6px',
    boxShadow: theme.boxShadow,
    cursor: 'pointer',
    ':before': {
      position: 'absolute',
      top: '50%',
      right: '22px',
      padding: '2px',
      borderColor: theme.baseTextColor,
      borderStyle: 'solid',
      borderWidth: '0px 1px 1px 0px',
      transform: 'translateY(-50%) rotate(45deg)',
      content: '""',
    },
    [`@media screen and (min-width: ${theme.breakPoint})`]: {
      paddingTop: '19px',
      paddingBottom: '17px',
      fontSize: '14px',
    },
  })),
  regionList: createStyle(({ theme }) => ({
    position: 'absolute',
    width: '100%',
    marginTop: '4px',
    paddingTop: '12px',
    paddingRight: '18px',
    paddingLeft: '18px',
    paddingBottom: '18px',
    backgroundColor: theme.baseBackgroundColor,
    borderRadius: '6px',
    boxShadow: theme.boxShadow,
  })),
  regionButton: createStyle(({ theme }) => ({
    paddingTop: '4px',
    paddingRight: '6px',
    paddingBottom: '4px',
    paddingLeft: '6px',
    color: theme.baseTextColor,
    fontFamily: theme.baseFontFamily,
    fontWeight: theme.lightFontWeight,
    fontSize: '12px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    [`@media screen and (min-width: ${theme.breakPoint})`]: {
      paddingTop: '6px',
      paddingBottom: '3px',
      fontSize: '14px',
    },
  })),
}
